### ISSUE TITLE
Icon/Logo not showing in "integrations" tab nor in HACS

### ISSUE THREAD

**Issue by VilkkuKoo** [sudoxnym/saas#1]
Icon/logo not showing in integrations tab nor in the hacs. i know this might not be huge or major but since the icon/logo is in the files i think it should be visible.

**Comment by sudoxreboot** [comment]
Not a bug. In order for the logo to properly appear, it requires approval from core. Core in this case was frenk, who told me my logo doesn't match the original logo, [Duh? I'm using my logo for my integration] so he won't add it and I asked him several times how to complete it and he ignored me.
