### ISSUE TITLE
Set alarm service - Possible to set captcha?

### ISSUE THREAD

**Issue by RealJustMe** [sudoxnym/saas#3]
Hi, is it possible to set a captcha (and maybe other settings) through the set alarm service? Or would it be possible to add this feature?

**Comment by sudoxreboot** [comment]
dude, so sorry for late reply, never got notice of this. unfortunately the alarm setting is controlled by android intents and the captcha is part of the app not part of the intents, so no way to really get that function as far as I can tell. Does it not set it to your default settings?

**Comment by RealJustMe** [comment]
I use SAA for all kinds of Alarms, Wake up, Medication, get ready etc. not all of them need a captcha so i don't have the captcha as default. I Would love to automate these, but I guess without an integration from urbandroid it won't happen.
Thanks anyway, still like your integration :)

**Comment by sudoxreboot** [comment]
https://www.docs.sleep.urbandroid.org/devs/intent_api.html
just so you're aware, it's got nothing to do with who made the integration, it has to do with what they provide in their intents, I can dismiss captchas, but not set them, and the dismiss kinda defeats the purpose since you still have to trigger the automation to dismiss it somehow.

**Comment by RealJustMe** [comment]
I meant more like if they made an official integration for Home Assistant, that way it would be possible to set the different extras.
Maybe I should ask Urbandroid if they could add captchas as an intent.

I have another quick question: `sensor.saas_*_alarm_event` has the ability to show the next alarm. Could you add an extra sensor that permanently shows the next alarm with title as an attribute since `sensor.saas_*_alarm_event` gets overwritten with other values when, i.e., sleep tracking starts?
